#!@bash@/bin/sh
B=/run/current-system/sw/share/local

ln -s ${B}/setup_auth ~sh/.kde/Autostart/
D=~sh/.config/pulse; mkdir $D && chown sh:sh ~sh/.config ~sh/.config/pulse; ln -s ${B}/default.pa ${B}/client.conf ${D}/
