{
 "title": "Envmon",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "envmon_co2", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Sensor ups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"envmon\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sensor locations",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "options": {
    "content": "1. Entertainment room\n2. Living room\n3. West porch"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "envmon_rh", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Electricity use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    { "expr": "rate(envmon_energy[130s])", "legendFormat": "{{port}}" },
    { "expr": "sum(rate(envmon_energy[130s]))", "legendFormat": "total" }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "envmon_temp", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Air pressure (kPa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "(envmon_press >= 90000)/1000", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Particulate Matter (ug/m**3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "avg_over_time(envmon_pm[8m])", "legendFormat": "<={{sz}} um" }
   ]
  },
  {
   "title": "Windows",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 28 },
   "targets": [
    { "expr": "e" },
    {
     "expr": "avg by () (envmon_temp{node=\"3\"})"
    },
    {
     "expr": "avg by () (envmon_pm{sz=\"2.5\", node=\"3\"})"
    }
   ]
  }
 ]
}