{
 "title": "Minecraft 0",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Connected players",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mc_player_list", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"jibril.x.s:20004\"}[300s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem RSS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"jibril.x.s:20004\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tick times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(mc_dimension_tick_seconds_sum[200s])/ rate(mc_dimension_tick_seconds_count[200s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mc_dimension_chunks_loaded", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "mc_entities_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}