{
 "title": "Node info",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "jibril.x.s.:9100,localhost:9100,liel.x.s.:9100,yalda.sh.s.:9100"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature (degC)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(node_thermal_zone_temp{instance=\"$node\"}[5m])",
     "legendFormat": "{{type}} {{zone}}"
    },
    { "expr": "30" }
   ]
  },
  {
   "title": "Filesystem /",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", instance=\"$node\"}-node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"$node\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", instance=\"$node\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}-node_memory_Cached_bytes{instance=\"$node\"}-node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) ( rate(node_cpu_seconds_total{mode!=\"idle\", instance=\"$node\"}[10m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Uptime (days)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{cpu=\"0\", instance=\"$node\"})/86400"
    }
   ]
  },
  {
   "title": "NF conntrack entries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\"}",
     "legendFormat": "N"
    }
   ]
  },
  {
   "title": "uptime (days)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{cpu=\"0\", instance=\"$node\"})/86400"
    }
   ]
  }
 ]
}