#!/bin/sh

export PATH=${coreutils}/bin:${findutils}/bin

O=${out}/share/lapps/${LINKNAME}

mkdir -p $O
[ "${LDEPS}" != "" ] && mkdir $O/lib
[ "${BDEPS}" != "" ] && mkdir $O/bin
[ "${JDEPS}" != "" ] && mkdir -p $O/share/java

for D in ${LDEPS}; {
    cd $D;
    for d in $(find lib -type d); {
	#echo $D $d
	mkdir ${O}/${d}
	ln -s $D/${d}/*so* ${O}/${d}/
    }
}
for D in ${BDEPS}; {
    ln -s ${D}/bin/* $O/bin/
}
for D in ${JDEPS}; {
    ln -s ${D}/share/java/* $O/share/java
}

RFN=${O}/run.sh

cat >$RFN <<EOF
#!${SH}/bin/sh
export LD_LIBRARY_PATH=${O}/lib/

for ld in ${glibc64}/lib/ld-linux*so* ${glibc32}/lib/ld-linux*so*; {
  echo -n "Trying \$ld ..."
  "\$ld" --verify "\$1" >/dev/null || {
    echo "failed."
    continue
  }
  echo ok.
  exec \$ld \$@
}
EOF

chmod a+x $RFN
